### ISSUE TITLE
Interface Design

### ISSUE THREAD

**Issue by nmjlelievre** [challett/meteor-stocks#10]
Ideas for a GUI structure.

**Comment by nmjlelievre** [comment]
![20151031_143632](https://cloud.githubusercontent.com/assets/6741032/10865282/13a405d6-7fdd-11e5-9919-8147ded09ffa.jpg)

**Comment by challett** [comment]
We're rolling an android app I thought.  This may be better suited to the cinematic experience of a desktop

**Comment by nmjlelievre** [comment]
Yeah I thought we were making a desktop app... Why don't we just make a dual compatible one that works in desktop and mobile chrome?

**Comment by challett** [comment]
Because we can submit an APK and I don't trust the TA's enough to wait when the meteor free servers say the app isn't available yet.. Anything that we make will be cross compatible, but I don't want it to depend on the server at all if possible.

And if we make a "website" he's going to say it wasn't "really software engineering" based on his response.. If we make an app he'll respect it more.  Plus there's tonnes of stock websites already.

**Comment by challett** [comment]
https://creator.ionic.io/share/c902e90c83eb

**Comment by nmjlelievre** [comment]
Quick flat-theme prototype idea.

![meteorstocks_home-min](https://cloud.githubusercontent.com/assets/6741032/10866192/3ab27964-7ffb-11e5-8ca5-cc56d3084b5b.png)

**Comment by challett** [comment]
I kinda feel like slitting my wrists.  I like the layout, it looks nice, but maybe the background should be a little lighter though

**Comment by nmjlelievre** [comment]
Lol yeah I was thinking that after i finished it. Everything can be changed it's just a jumping off point

**Comment by challett** [comment]
Is that the netflix font at the top?

**Comment by nmjlelievre** [comment]
No but it does look similar

**Comment by challett** [comment]
![capture](https://cloud.githubusercontent.com/assets/6461666/11327236/b9f5f62a-914d-11e5-9103-ed61bc2fa5fe.PNG)

**Comment by challett** [comment]
![capture](https://cloud.githubusercontent.com/assets/6461666/11327247/03b9a1da-914e-11e5-99f4-b4545b9d641a.PNG)

**Comment by nmjlelievre** [comment]
![20151125_135543](https://cloud.githubusercontent.com/assets/6741032/11406702/b6db2358-937c-11e5-95b6-1849bb0b78ad.jpg)

Design done before iphone mockup

**Comment by jadeesanton** [comment]
![img_0106](https://cloud.githubusercontent.com/assets/6778271/11406794/2d436d02-937d-11e5-90ac-d6ce76fd8caf.JPG)
![img_0107](https://cloud.githubusercontent.com/assets/6778271/11406793/2d41eeaa-937d-11e5-896d-c5835cce6e07.JPG)
