### ISSUE TITLE
Persona Creation

### ISSUE THREAD

**Issue by challett** [challett/meteor-stocks#11]
We need to make up a couple personas for milestone two.

So far I'm thinking of a business person who wants to know everything about the stocks and is bothered when it's not easy to get to.  And an average Joe who wants to keep track of the overall performance of the few stocks he is interested in and is bothered when he's presented with a whole bunch of information that he doesn't understand

**Comment by challett** [comment]
We need a total of three

**Comment by nmjlelievre** [comment]
https://www.overleaf.com/3761277nhxznn

To edit the document
