### ISSUE TITLE
CSS Framework Discussions

### ISSUE THREAD

**Issue by challett** [challett/meteor-stocks#12]
Ionic: http://ionicframework.com/
Polymer: https://www.polymer-project.org/1.0/

Personally the design I have in mind for this project would be suited for ionic.  But I am open to suggestions.  Toast is out of the question, we should use something more involved for this one to avoid excess work.  Other options include the obvious ones, bootstrap and materialize (Nick hates these ones)

**Comment by nmjlelievre** [comment]
Ionic looks more like iOS so it might be a good option since we're doing a mobile app (toggles and cards that users are used to seeing on mobile). Plus the Ionic animation is real smooth.

**Comment by challett** [comment]
Ionic is supposed to look like iOS when running on iOS and look like Android when running on Android.  I think most of the implemented components will adapt, but anything we add on top may not.  It's a plus!
