### ISSUE TITLE
Radio button for change and changeInPercent

### ISSUE THREAD

**Issue by speence** [challett/meteor-stocks#24]
User should only be able to select one or the other

![image](https://cloud.githubusercontent.com/assets/6643181/11609904/1e43bce4-9b61-11e5-8cf9-ca762c48b881.png)

![image](https://cloud.githubusercontent.com/assets/6643181/11609908/2a52bc74-9b61-11e5-90f3-7fd1eeb2ca5a.png)

**Comment by challett** [comment]
what?
